# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test & Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
      matrix:
        python-version: [3.8, 3.9]
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade poetry
        poetry install -v

    - name: Lint with black
      run: |
        poetry run black --check revizor tests
    
    - name: List with isort
      run: |
        poetry run isort --check revizor tests

    - name: Lint with mypy
      run: |
        poetry run mypy revizor

    - name: Test with pytest
      run: |
        poetry run pytest --cov-report term --cov=revizor tests/
